version: "3.1"
services:
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - cargoapp_data:/var/lib/postgres
volumes:
  cargoapp_data:
